- Dockerfile
- docker-compose-local.yml
- makefile
- tests/__init__.py
- tests/locust/test_sso.py
- tests/locust/test_ui.py
- tests/selenium/sso/test_login.py
[this task](https://uktrade.atlassian.net/browse/ED-255)
[relies on this change](https://github.com/uktrade/directory-ui/pull/219)
> Add test for good login

- makefile
- tests/smoke/test_buyer.py
- tests/smoke/test_sso.py
[this task](https://uktrade.atlassian.net/browse/ED-1015)
to run locally:
```sh
make test_smoke_buyer
make test_smoke_sso
make test_smoke_supplier
```
I will do a follow-up change to remove existing integration test logic and boilerplate.
> Add smoke tests for FAB

- Dockerfile
- README.md
- requirements.txt
- tests/__init__.py
- tests/locust/helpers.py
https://uktrade.atlassian.net/browse/ED-680
> [WIP] Upgrade to python3

- tests/functional/features/fab/profile.feature
This adds a scenario that doesn't need any code as it uses already existing step definitions.
> ED-1758 logout login from to fab

- tests/smoke/test_profile.py
[this task](https://uktrade.atlassian.net/browse/ED-1838)
> Update get verified user test to expect has_exported_before

- tests/functional/features/context_utils.py
- tests/functional/features/fab/profile.feature
- tests/functional/features/pages/fab_ui_build_profile_sector.py
- tests/functional/features/pages/fab_ui_confirm_export_status.py
- tests/functional/features/pages/fab_ui_edit_details.py
- tests/functional/features/pages/fab_ui_edit_online_profiles.py
- tests/functional/features/pages/fab_ui_edit_sector.py
- tests/functional/features/steps/fab_given_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
- tests/functional/features/utils.py
- tests/settings.py
This fixes tests that were failing due to the changes introduces in the various user flows.
> Fix registration flow steps

- Dockerfile-functional
- Dockerfile-smoke
- docker-compose.yml
this [ticket](https://uktrade.atlassian.net/browse/ED-2001)
Apart from that I've made the build output less verbose by enabling quiet mode when downloading `dockerize` and fetching python requirements.
> ED-2001 don't build container for unused selenium tests

- requirements_functional.ini
- requirements_functional.txt
- tests/functional/features/environment.py
- tests/functional/features/utils.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2003)
This will print out information about last:
* request URL, headers & body
* redirects (if present)
* response headers & content
This should help to quickly understand why any given scenario failed.
> ED-2003 better debug on failure

- requirements_functional.ini
- requirements_functional.txt
- tests/functional/features/environment.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/utils.py
Extract "main" error and form errors and print them to console, for easier debugging.
> ED-2021 print errors if possible

- tests/functional/features/context_utils.py
- tests/functional/features/pages/utils.py
- tests/functional/features/steps/fab_when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-1788)
This change should shorten the test execution time a bit.
> ED-1788 use pre-selected companies

- Dockerfile-functional
- Dockerfile-selenium
- Dockerfile-smoke
- makefile
This [ticket](https://uktrade.atlassian.net/browse/ED-2121)
> ED-2121 use latest version of Dockerize

- tests/functional/features/context_utils.py
- tests/functional/features/fas/search.feature
- tests/functional/features/pages/fas_ui_profile.py
- tests/functional/features/steps/fab_given_def.py
- tests/functional/features/steps/fab_given_impl.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
- tests/settings.py
updated existing 2 scenarios by adding options to find company by: company's slug, case study slug & sector
```gherkin
@ED-1746
@fas
@case-study
@profile
@verified
@published
@two-actors
@bug
@ED-1968
@fixed
Scenario: Buyers should be able to find Supplier by uniquely identifying words present on Supplier's case study
And "Peter Alder" is an unauthenticated supplier
And "Peter Alder" has created and verified profile for randomly selected company "Y"
When "Peter Alder" adds a complete case study called "no 1"
Then "Annette Geissinger" should be able to find company "Y" on FAS using words from case study "no 1"
| search using case study's |
| title                     |
| summary                   |
| description               |
| caption 1 …
```
> ED- 2109 search by slugs and case study sector

- .github/PULL_REQUEST_TEMPLATE.md
- tests/functional/features/context_utils.py
- tests/functional/features/db_utils.py
- tests/functional/features/fab/registration.feature
- tests/functional/features/pages/fab_ui_confirm_identity.py
- tests/functional/features/pages/fab_ui_verify_company.py
- tests/functional/features/pages/sso_ui_login.py
- tests/functional/features/steps/fab_given_def.py
- tests/functional/features/steps/fab_given_impl.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
- tests/functional/features/utils.py
this adds 2 new scenarios
```gherkin
@ED-2094
@profile
@verification
@letter
Scenario: Logged-in Supplier should be able to verify profile by using code and link from the letter
And "Annette Geissinger" confirmed her email address
And "Annette Geissinger" built the company profile
And "Annette Geissinger" set the company description
And "Annette Geissinger" received the letter with verification code
When "Annette Geissinger" goes to the verification link from the letter as authenticated user
And "Annette Geissinger" decides to verify her identity with the address
And "Annette Geissinger" submits the verification code …
```
> ED-2094 verify profile using link provided in the verification letter

- tests/functional/pages/fas_ui_feedback.py
- tests/functional/utils/context_utils.py
- tests/functional/utils/generic.py
Send dummy captcha response to the feedback (contact us) form.
> send captcha response with feebback form

- .circleci/config.yml
- makefile
- requirements_smoke.ini
- requirements_smoke.txt
This [ticket](https://uktrade.atlassian.net/browse/ED-2923)
In order to find out which links open in the same or new tab, I've modified `pylinkvalidator` https://github.com/bartdag/pylinkvalidator/pull/22 to show information about `target` attribute when `-S` parameter is used.
Moreover that PR includes a basic JSON reporter. Which can come in handy when you want to extract some details from report using e.g. [jq](https://stedolan.github.io/jq/)
*Check the links and display the progress:*
```bash
pylinkvalidate.py \
--progress \
--timeout=25 \
--depth=2 \
--workers=10 \
--types=a \
--test-outside \
--parser=lxml \
--header="User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.97 Safari/537.36 Vivaldi/1.94.1008.36" \ …
```
> ED-2923 Add links check

- tests/exred/environment.py
- tests/exred/features/home-page.feature
- tests/exred/pages/home.py
- tests/exred/steps/then_def.py
- tests/exred/steps/then_impl.py
- tests/exred/steps/when_def.py
- tests/exred/steps/when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-3014)
Scenario:
```gherkin
@ED-3014
@video
Scenario: Any Exporter should be able to play promotional video on the Home page
Given "Robert" visits the "Home" page
When "Robert" decides to watch "6" seconds of the promotional video
Then "Robert" should be able to watch at least first "5" seconds of the promotional video
@ED-3014
@video
Scenario: Any Exporter should be able to close the window with promotional video on the Home page
Given "Robert" visits the "Home" page
When "Robert" decides to watch "6" seconds of the promotional video
And "Robert" closes the window with promotional video
Then "Robert" should not see the window with promotional video
```
> ED-3014 promo video

- .behaverc
- .circleci/config.yml
- .gitignore
- makefile
- requirements_exred.ini
- requirements_exred.txt
- requirements_functional.ini
- requirements_functional.txt
- tests/exred/.behaverc
- tests/exred/features/header-footer.feature
- tests/exred/pages/header.py
- tests/exred/pages/home.py
- tests/exred/pages/triage_create_your_export_journey.py
- tests/exred/pavement.py
- tests/exred/registry/pages.py
- tests/exred/steps/when_def.py
- tests/exred/steps/when_impl.py
- tests/smoke/reports/.gitignore
This [ticket](https://uktrade.atlassian.net/browse/ED-3203)
Generate JUnit XML test reports from:
* smoke tests
* FABS integrations tests (and merge XML files using NPM [junit-merge](https://www.npmjs.com/package/junit-merge) package)
* ExRed functional tests (and merge XML files using NPM [junit-merge](https://www.npmjs.com/package/junit-merge) package)
> ED-3203 generate junit xml reports

- scripts/jira_to_geckoboard.py
This [ticket](https://uktrade.atlassian.net/browse/ED-3610)
> ED-3610 jira to geckboard script

- tests/exred/pages/article_common.py
- tests/exred/pages/article_list.py
- tests/exred/pages/common_actions.py
- tests/exred/pages/footer.py
- tests/exred/pages/guidance_common.py
- tests/exred/pages/header.py
- tests/exred/pages/home.py
- tests/exred/pages/interim_exporting_opportunities.py
- tests/exred/pages/international.py
- tests/exred/pages/personalised_journey.py
- tests/exred/pages/sso_confirm_your_email.py
- tests/exred/pages/sso_registration.py
- tests/exred/pages/sso_registration_confirmation.py
- tests/exred/pages/sso_sign_in.py
- tests/exred/pages/sso_sign_out.py
- tests/exred/pages/triage_are_you_registered_with_companies_house.py
- tests/exred/pages/triage_are_you_regular_exporter.py
- tests/exred/pages/triage_company_name.py
- tests/exred/pages/triage_do_you_use_online_marketplaces.py
- tests/exred/pages/triage_have_you_exported.py
- tests/exred/pages/triage_summary.py
- tests/exred/pages/triage_what_do_you_want_to_export.py
- tests/exred/utils/__init__.py
This [ticket](https://uktrade.atlassian.net/browse/ED-3609)
> ED-3609 fix scenarios failing on browserstack

- requirements_exred.in
- requirements_exred.txt
- tests/exred/config/browserstack-first-browser-set.json
- tests/exred/features/header-footer.feature
- tests/exred/features/home-page.feature
- tests/exred/features/personalised-page.feature
- tests/exred/features/top-importers.feature
- tests/exred/features/triage.feature
- tests/exred/pages/common_actions.py
- tests/exred/pages/personalised_journey.py
- tests/exred/pages/personalised_what_do_you_want_to_export.py
- tests/exred/pages/triage_have_you_exported.py
- tests/exred/pages/triage_what_do_you_want_to_export.py
- tests/exred/registry/pages.py
- tests/exred/steps/then_impl.py
- tests/exred/steps/when_def.py
- tests/exred/steps/when_impl.py
- tests/exred/utils/__init__.py
- tests/functional/environment.py
- tests/functional/features/fab/registration.feature
- tests/functional/pages/fab_ui_confirm_identity.py
- tests/functional/steps/fab_when_impl.py
- tests/settings.py
This [ticket](https://uktrade.atlassian.net/browse/ED-ED-3228)
> ED-3228 Update BDD scenarios for new triage flow & simplified letter verification process on FAB

- Dockerfile-smoke
- tests/exred/pages/home.py
- tests/functional/features/fas/languages.feature
- tests/functional/utils/generic.py
This [ticket](https://uktrade.atlassian.net/browse/ED-4130)
It also includes few fixes for the issues that surfaced at the same time.
PS. only dead URLs tests failed 
```
error (status=403): https://medium.com/legal-services-are-great
error (status=503): https://twitter.com/intent/tweet?text=Export%20Readiness%20-%20Sell%20overseas%20directly.../?source=persona_occasional
error (status=503): https://twitter.com/intent/tweet?text=Export%20Readiness%20-%20Choose%20the%20right%20finance%20.../?source=persona_occasional
```
> ED-4130 fix pip v10 issue

- .circleci/config.yml
- requirements_geckoboard.txt
- tests/exred/environment.py
This [ticket](https://uktrade.atlassian.net/browse/ED-3610)
It should refresh QA Geckoboard:
* At minute 0, 15, 30, and 45 
* past every hour from 8 through 19 
* on every day-of-week from Monday through Friday
> ED-3610 update geckoboard periodically

- .circleci/config.yml
This [ticket](https://uktrade.atlassian.net/browse/ED-3610)
> ED-3610 simplify CircleCI geckoboard updater job

- .circleci/config.yml
- scripts/geckoboard_updater.py
This [ticket](https://uktrade.atlassian.net/browse/ED-3659)
> ED-3659 fix query and cronjob

- .circleci/config.yml
- tests/exred/config/browserstack-first-browser-set.json
- tests/exred/config/browserstack-second-browser-set.json
- tests/exred/config/browserstack-single.json
- tests/exred/features/header-footer.feature
- tests/exred/pages/export_opportunities.py
- tests/exred/pages/invest_in_great.py
- tests/exred/steps/then_def.py
- tests/exred/steps/then_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-4220)
> ED-4220 fix scenarios failing due to IP geolocation

- scripts/geckoboard_updater.py
This [ticket](https://uktrade.atlassian.net/browse/TT-27)
> TT-37 get number of tickets closed today

- tests/functional/pages/fab_ui_verify_company.py
- tests/functional/utils/generic.py
This [ticket](https://uktrade.atlassian.net/browse/TT-134)
> TT-134 update failing tests

- tests/smoke/test_cms.py
This [ticket](https://uktrade.atlassian.net/browse/CM-208)
> CMS-208 ignore faulty cms urls

- requirements_browser.txt
- tests/browser/config/browserstack-first-browser-set.json
- tests/browser/features/invest/contact-us-and-leave-feedback.feature
- tests/browser/pages/__init__.py
- tests/browser/pages/invest/__init__.py
- tests/browser/pages/invest/contact_us.py
- tests/browser/pages/invest/contact_us_thank_you.py
- tests/browser/pages/invest/home.py
- tests/browser/pages/invest/industries.py
- tests/browser/pages/invest/industry.py
- tests/browser/pages/invest/uk_setup_guide.py
- tests/browser/pages/invest/uk_setup_guide_pages.py
- tests/browser/steps/given_def.py
- tests/browser/steps/when_def.py
- tests/browser/steps/when_impl.py
Scenario:
```gherkin
@CMS-163
@beta
@feedback
@header
@footer
Scenario Outline: Visitors should be able to access feedback form from "<selected>" page
Given "Robert" visits the "Invest - <selected>" page
When "Robert" decides to use "Feedback" link on "Invest - <selected>" page
Then "Robert" should be on the "Invest - Feedback" page
Examples: Various pages
| selected       |
| Home           |
| Industries     |
| UK Setup Guide |
Examples: Industry pages
| selected                                       |
| Advanced manufacturing - industry              |
| Aerospace - industry                           |
| Agri-tech - industry                           |
| Asset management - industry                    |
| Automotive - industry …
```
> CMS-163 invest - automated scenarios for Contact-us form

- Dockerfile-browser
- Dockerfile-functional
- Dockerfile-smoke
- tests/browser/environment.py
- tests/browser/features/exred/social-media.feature
- tests/browser/features/exred/triage.feature
- tests/browser/features/fas/home-page.feature
- tests/browser/features/fas/industries-page.feature
- tests/browser/features/fas/industry-pages.feature
- tests/browser/pages/common_actions.py
- tests/browser/pages/exread/share_on_linkedin.py
- tests/browser/pages/exread/share_on_twitter.py
- tests/browser/pages/exread/triage_company_name.py
- tests/browser/pages/exread/triage_create_your_export_journey.py
- tests/browser/pages/external/british_council_home.py
- tests/browser/pages/external/events_home.py
- tests/browser/pages/external/visit_britain_home.py
- tests/browser/pages/fas/contact_us.py
- tests/browser/pages/fas/home.py
- tests/browser/pages/fas/industries.py
- tests/browser/pages/fas/industry.py
- tests/browser/pages/fas/search_results.py
- tests/browser/pages/invest/contact_us.py
- tests/browser/pages/invest/industries.py
- tests/browser/pages/invest/industry.py
- tests/browser/steps/when_def.py
- tests/browser/steps/when_impl.py
Fix tests that are affected by recent changes
> Fix failing tests

- tests/__init__.py
- tests/conftest.py
- tests/functional/pages/fab_ui_edit_details.py
- tests/functional/steps/fab_given_impl.py
- tests/functional/steps/fab_when_impl.py
- tests/functional/utils/generic.py
- tests/smoke/test_buyer.py
- tests/smoke/test_cms.py
- tests/smoke/test_profile.py
- tests/smoke/test_supplier.py
- tests/smoke/test_supplier_redirects.py
Make certain smoke tests more reliable
> Make certain smoke tests more reliable

- tests/functional/features/fas/languages.feature
- tests/functional/utils/generic.py
- tests/smoke/cms_api_helpers.py
- tests/smoke/test_cms.py
- tests/smoke/test_supplier_redirects.py
This is a temporary fix for issues caused by [this bug](https://uktrade.atlassian.net/browse/CMS-550)
> CMS-550 Temp fix smoke tests

- tests/__init__.py
- tests/smoke/test_contact_us.py
- tests/smoke/test_soo.py
This [ticket](https://uktrade.atlassian.net/browse/XOT-683)
Add url check for all the five steps in Apply now via DIT
Run them from CLI
```
pytest --capture=no --verbose tests/smoke/test_contact_us.py -m "not stage and not prod" -x
```
> Link checkers

- locustfile_rudimental_soo.py
- tests/load/test_soo.py
- tests/load/utils.py
This [ticket](https://uktrade.atlassian.net/browse/XOT-685)
Scenario:
```
Load test for SOO home, search result & marketplace page
```
> Add load test for SOO landing page, search & marketplace

- tests/browser/features/soo/new-contact-us.feature
- tests/browser/pages/exred/contact_us_long_export_advice_business.py
- tests/browser/pages/exred/contact_us_long_export_advice_comment.py
- tests/browser/pages/exred/contact_us_long_export_advice_personal.py
- tests/browser/pages/exred/contact_us_office_finder.py
- tests/browser/pages/exred/contact_us_office_finder_search_results.py
- tests/browser/pages/exred/contact_us_short_domestic.py
- tests/browser/pages/exred/contact_us_short_feedback.py
- tests/browser/pages/exred/contact_us_soo_long_contact_details.py
- tests/browser/pages/exred/contact_us_soo_long_organisation_details.py
- tests/browser/pages/exred/contact_us_soo_long_your_business.py
- tests/browser/pages/exred/contact_us_soo_long_your_experience.py
- tests/browser/pages/exred/contact_us_triage_domestic.py
- tests/browser/pages/exred/contact_us_triage_export_opportunities.py
- tests/browser/pages/exred/contact_us_triage_export_opportunities_dedicated_support_content.py
- tests/browser/pages/exred/contact_us_triage_great_account.py
- tests/browser/pages/exred/contact_us_triage_great_account_dedicated_support_content.py
- tests/browser/pages/exred/contact_us_triage_great_services.py
- tests/browser/pages/exred/contact_us_triage_international.py
- tests/browser/pages/exred/contact_us_triage_location.py
- tests/browser/pages/exred/international_contact_us.py
- tests/browser/pages/soo/home.py
- tests/browser/pages/soo/search_results.py
- tests/browser/pages/sso/sign_in.py
- tests/browser/steps/given_def.py
- tests/browser/steps/when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/XOT-753)
> SOO: Submit of contact us form redirect to search page

- .circleci/config.yml
This [ticket](https://uktrade.atlassian.net/browse/XOT-754)
Scenario:
```
SOO - Integrate load test into Geckoboard
```
> Update circleci config to include load test for SOO

- .circleci/config.yml
- locustfile_rudimental_search.py
- makefile
- tests/__init__.py
- tests/load/test_search.py
- tests/load/test_soo.py
This [ticket](https://uktrade.atlassian.net/browse/XOT-805)
Scenario:
```
Add load test for search across great site
```
> Search: load test

- requirements_smoke.in
- requirements_smoke.txt
- tests/__init__.py
- tests/smoke/test_sitemaps.py
This [ticket](https://uktrade.atlassian.net/browse/TT-1582)
> TT-1582 add smoke tests for sitemaps

- CHANGELOG.md
- tests/browser/features/domestic/header-footer.feature
- tests/browser/pages/common_selectors.py
- tests/browser/steps/given_def.py
- tests/browser/steps/then_def.py
- tests/browser/steps/then_impl.py
- tests/browser/steps/when_def.py
- tests/browser/steps/when_impl.py
this detected that FAB's mobile header is wack
> Any mobile user should see mobile-friendly header

- directory_tests_shared/requirements.txt
- requirements_browser.txt
- requirements_functional.txt
- requirements_load.txt
- requirements_periodic_tasks.txt
- requirements_smoke.txt
This [ticket](https://uktrade.atlassian.net/browse/CMS-)
Scenario:
```gherkin
```
> Fix vulnerabilities

- requirements_browser.txt
This [ticket](https://uktrade.atlassian.net/browse/CMS-)
Scenario:
```gherkin
```
> Updated the security vulnerabilities for Pillow-8.1.1 to Pillow-8.2.0

- directory_tests_shared/requirements.in
- directory_tests_shared/requirements.txt
- requirements_browser.txt
- requirements_functional.txt
- requirements_load.txt
- requirements_periodic_tasks.txt
- requirements_smoke.txt
- requirements_test_tools.txt
This [ticket](https://uktrade.atlassian.net/browse/CMS-)
Scenario:
```gherkin
```
> Dependencies upgrade

- directory_tests_shared/requirements.in
- directory_tests_shared/requirements.txt
- requirements_browser.txt
- requirements_functional.txt
- requirements_load.txt
- requirements_periodic_tasks.txt
- requirements_smoke.txt
- requirements_test_tools.txt
This [ticket](https://uktrade.atlassian.net/browse/CMS-)
Scenario:
```gherkin
```
> Twisted upgrade
