uktrade/directory-tests

- makefile
- tests/locust/test_api.py
To make things simpler, these are load tests for cases when we give these views invalid data (easier to do this than set everything up on the api server).
> Api load tests for SMS verification and Email Verification

- docker-compose-local.yml
- docker/cmd-run.sh
- docker/env.json
- makefile
- tests/__init__.py
- tests/smoke/test_buyer.py
[this task](https://uktrade.atlassian.net/browse/ED-1015)
to run locally you will need to plug in valid SSO credentials:
```sh
SSO_USER_USERNAME=<username> SSO_USER_PASSWORD=<password> make test_smoke
```
The credentials have been added to circleci environment variables.
I will do a follow-up change to remove existing integration test logic and boilerplate.
> Add regression smoke tests

- tests/functional/features/context_utils.py
- tests/functional/features/fab/profile.feature
- tests/functional/features/steps/fab_given_def.py
- tests/functional/features/steps/fab_given_impl.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
This implements scenario where after verifying the company, Supplier can view the published profile on FAS
```gherkin
@ED-1727
@publish
@FAS
Scenario: Once verified Company Profile should be published on FAS
Given "Peter Alder" has created and verified profile for randomly selected company "Y"
When "Peter Alder" decides to view published profile
Then "Peter Alder" should be on FAS profile page of company "Y"
```
> ED-1727 view published profile on FAS

- tests/functional/features/fab/profile.feature
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
This implements scenario:
```gherkin
@ED-1740
@registration
Scenario: Some suppliers are not appropriate to feature in the FAB service
Given "Peter Alder" is an unauthenticated supplier
When "Peter Alder" randomly selects an active company without a profile identified by an alias "Company X"
And "Peter Alder" confirms that "Company X" is the correct one
And "Peter Alder" decides that the export status of his company is "No, we are not planning to sell overseas"
Then "Peter Alder" should be told that his company is currently not appropriate to feature in the FAB service
```
> ED-1740 Some suppliers are not appropriate to feature in the FAB service

- tests/functional/features/fab/profile.feature
- tests/functional/features/steps/fab_given_def.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_when_def.py
Our naming convention is `SSO/great.gov.uk account` and `Directory profile`.
I've updated all step definitions accordingly.
ps. best reviewed when #47 is merged.
> ED-1743 use proper naming convention

- tests/functional/features/fab/profile.feature
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
This implements:
```gherkin
@ED-1757
@verification
@email
Scenario: Suppliers without verified email should be told to verify the email address first before being able to log in
When "Annette Geissinger" attempts to sign in to Find a Buyer profile
Then "Annette Geissinger" should be told that she needs to verify her email address first
```
> ED-1757 verify email first before signing in

- tests/functional/features/fab/profile.feature
- tests/functional/features/steps/fab_given_def.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
BEST REVIEWED WHEN #49 is merged.
-------------------------------------------------------
This implements:
```gherkin
@ED-1769
@login
Scenario: Suppliers with unverified company profile should be able to logout and log back in
And "Annette Geissinger" confirmed her email address
And "Annette Geissinger" signed out from Find a Buyer service
When "Annette Geissinger" signs in to Find a Buyer profile
Then "Annette Geissinger" should be on edit Company's Directory Profile page
And "Annette Geissinger" should be told that her company has no description
```
> ED-1769 log out and log back in

- tests/functional/features/fab/profile.feature
- tests/functional/features/steps/fab_given_def.py
- tests/functional/features/steps/fab_given_impl.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
- tests/functional/features/utils.py
- tests/settings.py
This implements 2nd out 2 scenarios defined in https://uktrade.atlassian.net/browse/ED-1770
```gherkin
@ED-1770
@sso
@fab
@account
Scenario: Suppliers with a standalone SSO/great.gov.uk account should be able to create a Directory profile
Given "Peter Alder" has a verified standalone SSO/great.gov.uk account
And "Peter Alder" is signed in to SSO/great.gov.uk account
And "Peter Alder" selected an active company without a Directory Profile identified by an alias "Company X"
When "Peter Alder" provides valid details of selected company
And "Peter Alder" selects random sector the company is interested in working in
And "Peter Alder" provides her full name which will be used to sent the verification letter
And "Peter Alder" confirms the details which will be used to sent the verification …
```
> ED-1770 create dir profile after creating sso account - 2nd scenario

- tests/functional/features/utils.py
This should improve handling of fetching & deleting email messages from S3 by simply retrying to access the file few times before the test will fail.
The reason behind this workaround stems from the issue described here: https://stackoverflow.com/questions/13580335/amazon-s3-the-specified-key-does-not-exist-after-get-key-success
> ED-1787 improve fetching & deleting emails messages from S3

- tests/functional/features/fab/profile.feature
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
This implements:
```gherkin
@ED-1759
@profile
@logo
Scenario: Supplier should not be able to upload files other than images as company’s logo
Given "Peter Alder" has created and verified profile for randomly selected company "Y"
When "Peter Alder" attempts to upload a file of unsupported type as company's logo
| file                  | type                    |
| Anfiteatro_El_Jem.bmp | Bitmap                  |
| Anfiteatro_El_Jem.jp2 | JPEG 2000               |
| Kobe_Port_Tower.webp  | Web P                   |
| example.exe           | Windows executable file |
| example.com           | Windows executable file |
| example.sh            | Linux shell script      |
| example.bat           | Windows shell script    |
| example.txt           | text file               |
Then for every …
```
> ED-1759 upload invalid logos

- tests/functional/features/steps/fab_when_impl.py
- tests/functional/features/utils.py
Includes minor improvements to the common test code.
FYI: These `try, except` clauses around assertions, despite being a pretty ugly solution, they allow to nicely print out a custom assertion failure message and the traceback when we run the tests with  `--no-logcapture` mode on `CI`.
> ED-1807 improve helpers

- tests/functional/features/fab/profile.feature
- tests/functional/features/pages/fab_ui_confirm_export_status.py
- tests/functional/features/pages/fab_ui_edit_address.py
- tests/functional/features/pages/fab_ui_edit_details.py
- tests/functional/features/pages/fab_ui_edit_online_profiles.py
- tests/functional/features/pages/fab_ui_edit_sector.py
- tests/functional/features/pages/fab_ui_profile.py
- tests/functional/features/pages/fas_ui_profile.py
- tests/functional/features/steps/fab_given_def.py
- tests/functional/features/steps/fab_given_impl.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
- tests/functional/features/utils.py
What's changed:
* make Page Object free of behave `context`
* move all `actions` and `assertions` specific to any given Page to a dedicated Page Object
* replace clumsy logic in step implementation with aforementioned reusable `actions` & `assertions`
The reasoning behind the changes:
* group logical parts of the code together (Page Objects)
* remove `behave` (test framework) logic from Page Objects
* make the test code easier to maintain
* improve code re-usability
> ED-1807 Final refactoring PR - use PO actions and assertions

- tests/functional/features/fab/profile.feature
This PR adds 2 new scenarios:
```gherkin
@ED-1804
@fab
@case-study
@profile
Scenario: Supplier should be able to update multiple case studies for an unverified company
Given "Peter Alder" created an unverified profile for randomly selected company "Y"
And "Peter Alder" added a complete case study called "no 1"
And "Peter Alder" added a complete case study called "no 2"
And "Peter Alder" added a complete case study called "no 3"
When "Peter Alder" updates all the details of case study called "no 1"
And "Peter Alder" updates all the details of case study called "no 2"
And "Peter Alder" updates all the details of case study called "no 3"
Then "Peter Alder" should see all case studies on the FAB Company's Directory Profile page
@ED-1804
@fab
@case-study
@profile
Scenario: Supplier should be …
```
> ED-1804 - update multiple case studies

- .behaverc
- makefile
- tests/functional/features/environment.py
- tests/functional/features/pages/fab_ui_build_profile_address.py
- tests/functional/features/pages/fab_ui_edit_online_profiles.py
- tests/functional/features/pages/fab_ui_landing.py
- tests/functional/features/pages/fab_ui_profile.py
- tests/functional/features/pages/fas_ui_profile.py
- tests/functional/features/pages/int_api_ch_search.py
- tests/functional/features/pages/sso_ui_confim_your_email.py
- tests/functional/features/pages/utils.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_impl.py
- tests/functional/features/utils.py
[This ticket](https://uktrade.atlassian.net/browse/ED-1933)
This add a custom context manager for `with` statement that allows to:
* print the custom assertion message
* print the `traceback` (stack trace)
* raise the original `AssertionError` exception
in one go.
Apart from that:
* I've added a step to verify whether company is already registered with FAB or not
* added `--stop` parameter to `functional_tests` target in make file, which forces `behave` to stop the test run on first failure (can save us some time)
* make `behave` print to the console last recorded response content, should help to shorten the time required to analyse the reason behind the failure.
Here's an example of it in action:
```bash
$ behave -k --format progress3 --stop tests/functional/features -t exception …
```
> ED-1933 better logging and error handling

- tests/functional/features/fas/search.feature
- tests/functional/features/pages/fab_ui_confirm_company.py
- tests/functional/features/pages/fas_ui_find_supplier.py
- tests/functional/features/pages/utils.py
- tests/functional/features/steps/fab_given_def.py
- tests/functional/features/steps/fab_given_impl.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_impl.py
- tests/functional/features/utils.py
- tests/settings.py
This [ticket](https://uktrade.atlassian.net/browse/ED-1746)
This implements 2 scenarios:
```gherkin
@ED-1746
@fas
@case-study
@profile
@verified
@published
Scenario: Buyers should be able to find Supplier by uniquely identifying words present on any of Supplier's case studies
And "Peter Alder" is an unauthenticated supplier
And "Peter Alder" has created and verified profile for randomly selected company "Y"
When "Peter Alder" adds a complete case study called "no 1"
And "Peter Alder" adds a complete case study called "no 2"
And "Peter Alder" adds a complete case study called "no 3"
Then "Annette Geissinger" should be able to find company "Y" on FAS using any part of case study "no 1"
And "Annette Geissinger" should be able to find company "Y" on FAS …
```
> ED-1746 more find by case study details scenarios

- requirements_functional.ini
- requirements_functional.txt
- tests/functional/features/fas/search.feature
- tests/functional/features/pages/fab_ui_case_study_basic.py
- tests/functional/features/pages/fab_ui_case_study_images.py
- tests/functional/features/pages/fab_ui_edit_address.py
- tests/functional/features/pages/fab_ui_edit_details.py
- tests/functional/features/pages/fab_ui_edit_online_profiles.py
- tests/functional/features/pages/utils.py
- tests/functional/features/steps/fab_given_impl.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-1967)
```gherkin
@ED-1967
@fas
@search
@profile
@verified
@published
Scenario: Buyers should be able to find Supplier by uniquely identifying words present on Supplier's profile
And "Peter Alder" is an unauthenticated supplier
And "Peter Alder" has created and verified profile for randomly selected company "Y"
And "Peter Alder" has added links to online profiles
| online profile  |
| Facebook        |
| LinkedIn        |
| Twitter         |
When "Annette Geissinger" searches for company "Y" on FAS using selected company's details
| company detail |
| title          |
| number         |
| keywords       |
| website        |
| summary        |
| description    |
| facebook       |
| twitter        | …
```
> ED-1967 find Supplier on FAS by company's details

- tests/functional/features/fas/search.feature
- tests/functional/features/pages/fab_ui_edit_details.py
- tests/functional/features/pages/fas_ui_find_supplier.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
- tests/functional/features/utils.py
This implements scenario for this (ticker](https://uktrade.atlassian.net/browse/ED-2000)
```gherkin
@ED-2000
@fas
@search
Scenario: Empty search query should return no results
When "Annette Geissinger" searches for companies on FAS with empty search query
Then "Annette Geissinger" should be told that the search did not match any UK trade profiles
```
> ED-2000 FAS: empty search query

- tests/__init__.py
- tests/functional/features/context_utils.py
- tests/functional/features/environment.py
- tests/functional/features/fas/feedback.feature
- tests/functional/features/pages/fas_ui_feedback.py
- tests/functional/features/pages/utils.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2012)
Implements:
```gherkin
@ED-2012
@feedback
Scenario: Buyer should be able to send us a feedback from "Industries" FAS page
When "Annette Geissinger" sends a Trade Profiles feedback request from "Industries" FAS page
Then "Annette Geissinger" should be told that the feedback request has been submitted
```
> ED-2012 FAS: send feedback

- tests/functional/features/fas/search.feature
- tests/functional/features/pages/utils.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2020)
```gherkin
@ED-2020
@search
Scenario: Buyers should be able to find Suppliers by product, service or company keyword
When "Annette Geissinger" searches for Suppliers using product name, service name and a keyword
| product                      | service                                  | keyword                    | company                                                  |
| Aerosol Paints               | Supply all types of Aerosols             | vanishing spray            | KING OF PAINTS                                           |
| LINSIG traffic signal models | management of transport                  | drainage civil engineering | CALLIDUS TRANSPORT & ENGINEERING LTD …
```
> ED-2020 find supplier by product, service or keyword

- tests/functional/features/fab/profile.feature
- tests/functional/features/pages/fab_ui_build_profile_basic.py
- tests/functional/features/pages/fas_ui_contact.py
- tests/functional/features/pages/utils.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
- tests/functional/features/utils.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2141)
Apart from the regular scenario I've also included:
* an extra one for bug https://uktrade.atlassian.net/browse/ED-2170
* tiny improvement to handle companies with `&` and `'` in their names
```gherkin
@ED-2141
@profile
Scenario: Supplier should not be able to use other characters than alphanumerics and commas in profile keywords
And "Annette Geissinger" confirmed her email address
When "Annette Geissinger" provides company details using following values
|company name  |website       |keywords         |separator |size    |error …
```
> ED-2141 only alphanumerics are allowed in profile keywords

- tests/functional/features/fas/industries.feature
- tests/functional/features/pages/common.py
- tests/functional/features/pages/fas_ui_creative_industry.py
- tests/functional/features/pages/fas_ui_creative_industry_summary.py
- tests/functional/features/pages/fas_ui_food_and_drink_industry.py
- tests/functional/features/pages/fas_ui_food_and_drink_industry_summary.py
- tests/functional/features/pages/fas_ui_health_industry.py
- tests/functional/features/pages/fas_ui_health_industry_summary.py
- tests/functional/features/pages/fas_ui_industries.py
- tests/functional/features/pages/fas_ui_tech_industry.py
- tests/functional/features/pages/fas_ui_tech_industry_summary.py
- tests/functional/features/pages/utils.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
These 2 tickets: [ED-2013](https://uktrade.atlassian.net/browse/ED-2013) & [ED-2015](https://uktrade.atlassian.net/browse/ED-2015)
This adds 2 new scenarios:
```gherkin
@ED-2013
@industries
Scenario: Buyers should be able to view page with promoted Industries
When "Annette Geissinger" visits "Industries" page on FAS
Then "Annette Geissinger" should see sections with selected industries
| industry       |
| Health         |
| Tech           |
| Creative       |
| Food and drink |
@ED-2015
@industries
Scenario Outline: Buyers should be able to find out more about every promoted industry - visit "<selected>" page
When "Annette Geissinger" visits "<selected>" page on FAS
Then "Annette Geissinger" should be presented …
```
> ED-2013 view industries

- tests/functional/features/fas/industries.feature
- tests/functional/features/steps/fab_given_def.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2016)
```gherkin
@ED-2016
@industries
Scenario Outline: Buyers should be able to find UK Suppliers by industries associated with promoted Case Study on "<selected>" page
And "Annette Geissinger" is on the "<selected>" page on FAS
When "Annette Geissinger" follows all the links to industries associated with the case study from the Company Showcase
Then "Annette Geissinger" should see search results filtered by appropriate industries
Examples:
| selected                        |
| Health Industry                 |
| Tech Industry                   |
| Creative Industry               |
| Food and drink Industry         |
| Health Industry Summary         |
| Tech Industry Summary           |
| …
```
> ED-2016 find suppliers by showcase case study industries

- tests/functional/features/fas/industries.feature
- tests/functional/features/fas/search.feature
- tests/functional/features/pages/common.py
- tests/functional/features/pages/fas_ui_find_supplier.py
- tests/functional/features/pages/utils.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2017)
```gherkin
@ED-2017
@filter
@sector
@search
Scenario: Buyers should be able to browse UK Suppliers by any of available sectors
When "Annette Geissinger" browse Suppliers by every available sector filter
Then "Annette Geissinger" should see search results filtered by appropriate sector
```
> ED-2017 filter by sector

- tests/functional/features/fas/search.feature
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2018)
```gherkin
@ED-2018
@filter
@sector
@search
Scenario: Buyers should be able to browse UK Suppliers by multiple sectors at once
When "Annette Geissinger" browse Suppliers by multiple sector filters
Then "Annette Geissinger" should see search results filtered by appropriate sectors
@ED-2018
@filter
@sector
@search
@invalid
Scenario: Buyers should NOT be able to browse UK Suppliers by invalid sectors
When "Annette Geissinger" attempts to browse Suppliers by invalid sector filter
Then "Annette Geissinger" should be told that the search did not match any UK trade profiles
```
> ED-2018 filter by multiple sectors

- tests/functional/features/fas/search.feature
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2019)
```gherkin
@ED-2019
@filter
@sector
@search
Scenario: Buyers should be able to clear search results filters
When "Annette Geissinger" browse Suppliers by multiple sector filters
And "Annette Geissinger" clears the search filters
Then "Annette Geissinger" should be told that the search did not match any UK trade profiles
And "Annette Geissinger" should see that search results are not filtered by any sector
```
> ED-2019 Buyers should be able to clear the filter results

- tests/smoke/test_profile.py
since [this PR](https://github.com/uktrade/directory-api/pull/313) has been merged, `is_company_owner` has changed value.
> Fix supplier "is_company_owner" boolean

- tests/functional/features/sso/profile.feature
This [ticket](https://uktrade.atlassian.net/browse/ED-2145)
Scenario:
```gherkin
@ED-2145
@sso
@account
Scenario: Suppliers should not be able to register with the same email again
Given "Peter Alder" is an unauthenticated supplier
When "Peter Alder" creates a SSO/great.gov.uk account
Then "Peter Alder" should be told about the verification email
When "Peter Alder" creates a SSO/great.gov.uk account
Then "Peter Alder" should be told about the verification email
```
> ED-2145 can't register with the same email address

- tests/functional/features/fab/case_studies.feature
- tests/functional/features/fas/search.feature
- tests/functional/features/pages/fab_ui_case_study_images.py
- tests/functional/features/pages/utils.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
- tests/settings.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2142) & this [bug ticket](https://uktrade.atlassian.net/browse/ED-2248)
Scenario:
```gherkin
@ED-2142
@fab
@case-study
@profile
Scenario: Supplier should not be able to use invalid values when adding a case study
Given "Peter Alder" created an unverified profile for randomly selected company "Y"
When "Peter Alder" attempts to add a case study using following values
|field         |value type      |separator |error                                                                                |
|title         |61 characters   |          |Ensure this value has at most 60 characters (it has 61).                             |
|title         |empty string    |          |This field is required. …
```
> ED-2142 case study input data validation

- tests/functional/features/context_utils.py
- tests/functional/features/fas/languages.feature
- tests/functional/features/pages/profile_ui_landing.py
- tests/functional/features/pages/sso_ui_logout.py
- tests/functional/features/pages/sso_ui_password_reset.py
- tests/functional/features/pages/utils.py
- tests/functional/features/sso/password.feature
- tests/functional/features/steps/fab_given_def.py
- tests/functional/features/steps/fab_given_impl.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
- tests/functional/features/utils.py
- tests/settings.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2146)
Scenario:
```gherkin
@ED-2146
@sso
@account
@manage
@password
Scenario: Suppliers without FAB profile should be able to reset password
Given "Peter Alder" has a verified standalone SSO/great.gov.uk account
And "Peter Alder" is signed out from SSO/great.gov.uk account
When "Peter Alder" resets the password
Then "Peter Alder" should be told that password was reset
And "Peter Alder" should receive a password reset email
```
> ED-2146 reset password for users with just SSO account

- tests/functional/features/pages/sso_ui_login.py
- tests/functional/features/sso/profile.feature
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2147)
Scenario:
```gherkin
@ED-2147
@sso
@account
Scenario: Suppliers should be able to sign out and sign back in
Given "Peter Alder" has a verified standalone SSO/great.gov.uk account
And "Peter Alder" is signed out from SSO/great.gov.uk account
When "Peter Alder" signs in to SSO/great.gov.uk account
Then "Peter Alder" should be signed in to SSO/great.gov.uk account
```
> ED-2147 Users with just SSO account should be able to sign back in

- tests/functional/features/context_utils.py
- tests/functional/features/fas/search.feature
- tests/functional/features/pages/sso_ui_change_password.py
- tests/functional/features/pages/sso_ui_confim_your_email.py
- tests/functional/features/pages/sso_ui_invalid_password_reset_link.py
- tests/functional/features/pages/sso_ui_password_reset.py
- tests/functional/features/pages/utils.py
- tests/functional/features/sso/password.feature
- tests/functional/features/sso/profile.feature
- tests/functional/features/steps/fab_given_def.py
- tests/functional/features/steps/fab_given_impl.py
- tests/functional/features/steps/fab_then_def.py
- tests/functional/features/steps/fab_then_impl.py
- tests/functional/features/steps/fab_when_def.py
- tests/functional/features/steps/fab_when_impl.py
- tests/functional/features/utils.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2251)
I've replaced scenarios that only assert password reset email delivery with "fully-bodied" ones that use that link to reset (change) the password.
Scenario:
```gherkin
@ED-2146
@sso
@account
@manage
@password
Scenario: Suppliers with just SSO/great.gov.uk account should be able to reset password
Given "Peter Alder" has a verified standalone SSO/great.gov.uk account
And "Peter Alder" signed out from SSO/great.gov.uk account
And "Peter Alder" received a password reset email
When "Peter Alder" changes the password to a new one using the password reset link
Then "Peter Alder" should be on Welcome to your great.gov.uk profile page
@ED-2251
@sso
@account
@manage
@password
Scenario: Suppliers with unverified FAB profile should be able …
```
> ED-2251 reset password for users with FAB profile

- tests/functional/features/fab/export-preference.feature
- tests/functional/pages/fab_ui_build_profile_sector.py
- tests/functional/steps/fab_then_def.py
- tests/functional/steps/fab_then_impl.py
- tests/functional/steps/fab_when_def.py
- tests/functional/steps/fab_when_impl.py
- tests/functional/utils/generic.py
- tests/functional/utils/request.py
This [ticket](https://uktrade.atlassian.net/browse/ED-1952).
This PR also contains a scenario for [bug ED-2313](https://uktrade.atlassian.net/browse/ED-2313)
Scenario:
```gherkin
@ED-1952
@profile
@export-preferences
Scenario Outline: Suppliers can select preferred countries of export from the given list and provide a list of other countries
And "Annette Geissinger" confirmed her email address
When "Annette Geissinger" provides valid details of selected company
And "Annette Geissinger" selects sector the company is in and "<preferred>" & "<other>" as other countries of export
Then "Annette Geissinger" should be asked to …
```
> ED-1952 preferred countries

- tests/exred/features/guidance.feature
- tests/exred/pages/footer.py
- tests/exred/pages/guidance_common.py
- tests/exred/pages/header.py
- tests/exred/pages/home.py
- tests/exred/pages/triage_result.py
- tests/exred/steps/given_def.py
- tests/exred/steps/given_imp.py
- tests/exred/steps/then_def.py
- tests/exred/steps/then_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2467).
Scenario:
```gherkin
@ED-2467
@banner
@<category>
@<location>
Scenario Outline: Guidance Banner should be visible when on "<category>" Guidance Article List accessed via "<location>"
Given "Robert" accessed "<category>" guidance articles using "<location>"
Then "Robert" should see the Guidance Navigation Ribbon
And "Robert" should see that the banner tile for "<category>" category is highlighted
Examples: header menu
| category                  | location    |
| Market research           | header menu |
| Customer insight          | header menu |
| Finance                   | header menu |
| Business planning         | header menu |
| Getting paid              | header menu |
| Operations and Compliance | header menu |
Examples: …
```
> ED-2467 guidance banner

- tests/exred/environment.py
- tests/exred/features/guidance.feature
- tests/exred/pages/guidance_common.py
- tests/exred/steps/then_def.py
- tests/exred/steps/then_impl.py
Scenario:
```gherkin
@ED-2463
@home-page
@articles
@<specific>
Scenario Outline: Any Exporter should get to a "<specific>" article list from Guidance section on the home page
Given "Robert" visits the "Home" page for the first time
When "Robert" goes to the "<specific>" Guidance articles via "home page"
Then "Robert" should see an ordered list of all articles selected for "<specific>" category
And "Robert" should see on the Guidance Articles page "Articles Read counter, Total number of Articles, Time to complete remaining chapters"
And "Robert" should see a link to the "<next>" Guidance category
Examples: Guidance categories
| specific          | next              |
| Market research   | Customer insight  |
| Customer insight  | …
```
> ED-2463 article list

- tests/exred/features/guidance.feature
This [ticket](https://uktrade.atlassian.net/browse/ED-2466)
Scenario:
```gherkin
@ED-2466
@personalised-page
@articles
@regular
@optimize
@<specific>
Scenario Outline: Regular Exporter should see "<specific>" Guidance Articles accessed via personalised journey page
Given "Nadia" was classified as "regular" exporter in the triage process
When "Nadia" goes to the "<specific>" Guidance articles via "personalised journey"
Then "Nadia" should see an ordered list of all articles selected for "<specific>" category
And "Nadia" should see on the Guidance Articles page "Articles Read counter, Total number of Articles, Time to complete remaining chapters"
And "Nadia" should see a link to the "<next>" Guidance category
Examples: Guidance categories
| specific          | next              |
| Market …
```
> ED-2466 Regular Exported should see ordered Guidance articles accessed via Personalised Journey page

- makefile
- requirements_exred.ini
- requirements_exred.txt
- tests/exred/README.md
- tests/exred/config/__init__.py
- tests/exred/config/browserstack-single.json
- tests/exred/environment.py
- tests/exred/features/guidance.feature
- tests/exred/features/home-page.feature
- tests/exred/features/triage.feature
- tests/exred/pages/guidance_common.py
- tests/exred/pages/home.py
- tests/exred/pages/personalised_journey.py
- tests/exred/pages/triage_company_name.py
- tests/exred/pages/triage_result.py
- tests/exred/pages/triage_what_do_you_want_to_export.py
- tests/exred/pavement.py
- tests/exred/registry/pages.py
- tests/exred/settings.py
- tests/exred/steps/given_def.py
- tests/exred/steps/then_def.py
- tests/exred/steps/then_impl.py
- tests/exred/steps/when_def.py
- tests/exred/steps/when_impl.py
- tests/exred/utils/__init__.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2520)
As steps were common for most of the `Triage` scenarios I've automated all following scenarios:
Scenario:
```gherkin
@ED-2520
@first-time
@regular
Scenario Outline: Regular Exporter visiting the home page for the 1st time should be able to get to personalised page after going through triage process
Given "Nadia" visits the "Home" page for the first time
And "Nadia" decided to build her exporting journey
When "Nadia" says what does she wants to export
And "Nadia" says that she "has" exported before
And "Nadia" says that exporting is "a regular" part of her business
And "Nadia" says that her company "is" incorporated
And "Nadia" "<company_name_action>" her company name
And "Nadia" sees the summary page with answers to the questions …
```
> ED-2520, ED-2521 & ED-2522 triage scenarios or new, occasional & regular exporters

- tests/exred/features/triage.feature
- tests/exred/pages/triage_are_you_registered_with_companies_house.py
- tests/exred/pages/triage_are_you_regular_exporter.py
- tests/exred/pages/triage_company_name.py
- tests/exred/pages/triage_do_you_use_online_marketplaces.py
- tests/exred/pages/triage_have_you_exported.py
- tests/exred/pages/triage_what_do_you_want_to_export.py
- tests/exred/registry/articles.py
- tests/exred/steps/then_def.py
- tests/exred/steps/when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2523)
Scenario:
```gherkin
@ED-2523
@first-time
@<specific>
Scenario Outline: "<specific>" Exporter should be able to change their answers to at the end of triage
Given "Robert" was classified as "<specific>" exporter in the triage process
When "Robert" decides to change his answers
Then "Robert" should be able to answer the triage questions again with his previous answers pre-populated
Examples: classifications
| specific   |
| New        |
| Occasional |
| Regular    |
```
> ED-2523 change triage answers

- tests/exred/features/guidance.feature
- tests/exred/features/home-page.feature
- tests/exred/pages/export_readiness_common.py
- tests/exred/pages/home.py
- tests/exred/pages/personalised_journey.py
- tests/exred/registry/articles.py
- tests/exred/steps/then_def.py
- tests/exred/steps/then_impl.py
- tests/exred/steps/when_def.py
- tests/exred/steps/when_impl.py
Scenario:
```gherkin
@ED-2366
@personas
@articles
Scenario Outline: "<exporter_status>" Exporter should be able to get to a relevant Export Readiness Article List from Personas section on the home page
Given "Robert" classifies himself as "<specific>" exporter
When "Robert" goes to the Export Readiness Articles for "<specific>" Exporters via "home page"
Then "Robert" should see an ordered list of all Export Readiness Articles selected for "<specific>" Exporters
And "Robert" should see on the Export Readiness Articles page "Articles Read counter, Total number of Articles, Time to complete remaining chapters"
Examples:
| specific   |
| New        |
| Occasional |
| Regular    |
```
> ED-2366 Exporters should be able to get to a relevant Export Readiness Article List from Personas section on the home page

- tests/exred/features/home-page.feature
- tests/exred/features/personalised-page.feature
- tests/exred/features/triage.feature
- tests/exred/pages/personalised_journey.py
- tests/exred/steps/given_def.py
- tests/exred/steps/then_def.py
- tests/exred/steps/then_impl.py
- tests/exred/steps/when_impl.py
These tickets:
* [ED-2588](https://uktrade.atlassian.net/browse/ED-2588)
* [ED-2589](https://uktrade.atlassian.net/browse/ED-2589)
* [ED-2590](https://uktrade.atlassian.net/browse/ED-2590)
Three birds with one stone.
Scenario:
```gherkin
@ED-2588
@personalised-page
@regular
Scenario Outline: Regular Exporter should see "<expected>" sections on personalised page
Given "Nadia" exports "<goods_or_services>"
And "Nadia" was classified as "Regular" Exporter which "<has_or_has_not>" incorporated the company
When "Nadia" decides to create her personalised journey page
Then "Nadia" should be on the Personalised Journey page for "regular" exporters
And "Nadia" should see "<expected>" sections on "personalised journey" page
Examples:
| goods_or_services | has_or_has_not | expected …
```
> ED-2588, ED-2589 & ED-2590 customised page

- tests/exred/features/articles.feature
- tests/exred/pages/article_common.py
- tests/exred/pages/guidance_common.py
- tests/exred/registry/articles.py
- tests/exred/steps/given_def.py
- tests/exred/steps/then_def.py
- tests/exred/steps/then_impl.py
- tests/exred/steps/when_def.py
- tests/exred/steps/when_impl.py
- tests/exred/utils/__init__.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2606)
Scenario:
```gherkin
@ED-2606
@guidance
@articles
Scenario Outline: Any Exporter accessing Articles through the Guidance Article List should be able to navigate to the next article
Given "Robert" accessed "<category>" guidance articles using "home page"
And "Robert" opened first Article from the list
When "Robert" decides to read through all Articles from selected list
Then "Robert" should be able to navigate to the next article from the List following the Article Order
Examples: home page
| category                  |
| Market research           |
| Customer insight          |
| Finance                   |
| Business planning         |
| Getting paid              |
| Operations and Compliance |
```
> ED-2606 navigate through guidance articles

- tests/exred/features/articles.feature
- tests/exred/pages/article_common.py
- tests/exred/steps/then_def.py
- tests/exred/steps/then_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2616)
Scenario:
```gherkin
@ED-2616
@guidance
@articles
Scenario Outline: Any Exporter accessing the last Article from the Guidance Article "<category>" List should be able to navigate to the "<next>" Articles
Given "Robert" accessed "<category>" guidance articles using "home page"
And "Robert" opened any Article but the last one
When "Robert" decides to read through all remaining Articles from selected list
Then "Robert" should see a link to the fist article from the "<next>" category
Examples:
| category                  | next                      |
| Market research           | Customer insight          |
| Customer insight          | Finance                   |
| Finance                   | Business planning         |
| Business …
```
> ED-2616 there should be no link to next article when Exporter reaches last article

- circle.yml
- tests/exred/environment.py
- tests/exred/features/articles.feature
- tests/exred/pages/article_common.py
- tests/exred/pages/export_readiness_common.py
- tests/exred/pages/footer.py
- tests/exred/pages/guidance_common.py
- tests/exred/pages/header.py
- tests/exred/pages/home.py
- tests/exred/steps/given_def.py
- tests/exred/steps/then_def.py
- tests/exred/steps/then_impl.py
- tests/exred/steps/when_def.py
- tests/exred/steps/when_impl.py
- tests/exred/utils/__init__.py
- tests/functional/pages/sso_ui_login.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2605)
Scenario:
```gherkin
@ED-2605
@progress
Scenario Outline: Any Exporter should see his progress through the articles list
Given "Robert" is on the "<group>" Article List for randomly selected category
When "Robert" opens any article on the list
And "Robert" goes back to the Article List page
Then "Robert" should see this article as read
And "Robert" should see that Article Read Counter increased by "1"
And "Robert" should see that Time to Complete remaining chapters decreased
Examples: article groups
| group            |
| Export Readiness |
| Guidance         |
```
> ED-2605 read progress

- tests/exred/features/articles.feature
This [ticket](https://uktrade.atlassian.net/browse/ED-2628)
Scenario:
```gherkin
@ED-2628
@articles
@<relevant>
@<location>
Scenario Outline: "<relevant>" Exporter should see a list of relevant Export Readiness Articles when accessed via "<location>"
Given "Robert" classifies himself as "<specific>" exporter
When "Robert" goes to the Export Readiness Articles for "<relevant>" Exporters via "<location>"
Then "Robert" should see an ordered list of all Export Readiness Articles selected for "<relevant>" Exporters
And "Robert" should see on the Export Readiness Articles page "Articles Read counter, Total number of Articles, Time to complete remaining chapters"
Examples:
| relevant   | location      |
| New        | header menu   |
| Occasional | header menu   |
| Regular    | header menu   | …
```
> ED-2628 relevant list of export readiness articles

- requirements_exred.ini
- requirements_exred.txt
- tests/exred/features/accessing-services.feature
- tests/exred/features/articles.feature
- tests/exred/features/guidance.feature
- tests/exred/features/personalised-page.feature
- tests/exred/features/triage.feature
- tests/exred/pages/events.py
- tests/exred/pages/export_opportunities.py
- tests/exred/pages/get_finance.py
- tests/exred/pages/header.py
- tests/exred/pages/home.py
- tests/exred/pages/interim_exporting_opportunities.py
- tests/exred/pages/triage_are_you_registered_with_companies_house.py
- tests/exred/steps/given_def.py
- tests/exred/steps/then_def.py
- tests/exred/steps/when_def.py
- tests/exred/steps/when_impl.py
These tickets:
* [ED-2770](https://uktrade.atlassian.net/browse/ED-2770)
* [ED-2771](https://uktrade.atlassian.net/browse/ED-2771)
Scenario:
```gherkin
@bug
@ED-2807
@fixme
@ED-2770
@session
Scenario Outline: An Exporter should be able to sing in from the Articles list page using "<element>" Sign-in link in order to save their reading progress for "<group>" articles
Given "Robert" is a registered and verified user
And "Robert" went to the "Home" page
And "Robert" went to randomly selected "<group>" Article category via "<location>"
And "Robert" read "<a number>" of articles
And "Robert" is on the "Article list" page
When "Robert" signs in using link visible in the "<element>"
Then "Robert" should be on the "Article List" page
And "Robert" should see his reading progress same as before …
```
> ED-2770 & ED-2770 sign in to save progress

- tests/exred/environment.py
- tests/exred/features/articles.feature
- tests/exred/pages/article_common.py
- tests/exred/pages/header.py
- tests/exred/pages/home.py
- tests/exred/pages/personalised_journey.py
- tests/exred/pages/sso_sign_out.py
- tests/exred/registry/articles.py
- tests/exred/registry/pages.py
- tests/exred/settings.py
- tests/exred/steps/then_def.py
- tests/exred/steps/then_impl.py
- tests/exred/steps/when_def.py
- tests/exred/steps/when_impl.py
- tests/exred/utils/__init__.py
- tests/functional/features/sso/password.feature
- tests/functional/steps/fab_when_def.py
- tests/functional/steps/fab_when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2773)
Scenario:
```gherkin
@ED-2773
@session
@<group>
@<location>
Scenario Outline: A signed in Exporter's progress should be updated with temporary information (cookie data merged with persistent storage)
Given "Robert" is a registered and verified user
And "Robert" is signed in
And "Robert" went to the "Home" page
And "Robert" went to randomly selected "<group>" Article category via "<location>"
And "Robert" read "<a number>" of articles and stays on the last read article page
When "Robert" signs out
And "Robert" goes to the "Home" page
And "Robert" goes back to the same "<group>" Article category via "<location>"
And "Robert" opens any Article but the last one
And "Robert" decides to read through all remaining Articles from selected …
```
> ED-2773 merge reading progress

- tests/exred/features/articles.feature
- tests/exred/pages/article_common.py
- tests/exred/pages/share_on_facebook.py
- tests/exred/pages/share_on_linkedin.py
- tests/exred/pages/share_on_twitter.py
- tests/exred/registry/pages.py
- tests/exred/steps/then_def.py
- tests/exred/steps/then_impl.py
- tests/exred/steps/when_def.py
- tests/exred/steps/when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-2640)
Scenario:
```gherkin
@ED-2640
@sharing
@<group>
@<social_media>
Scenario Outline: Any Exporter should be able to share the article via "<social_media>"
Given "Robert" is on the "<group>" Article List for randomly selected category
And "Robert" opened any Article
When "Robert" decides to share the article via "<social_media>"
Then "Robert" should be taken to a new tab with the "<social_media>" share page opened
And "Robert" should that "<social_media>" share page has been pre-populated with message and the link to the article
Examples:
| group            | social_media |
| Export Readiness | Facebook     |
| Guidance         | Twitter      |
| Export Readiness | LinkedIn     |
@ED-2640
@sharing
@<group>
@<social_media>
Scenario …
```
> ED-2640 share article on social media and via email

- tests/exred/features/case-studies.feature
- tests/exred/features/home-page.feature
- tests/exred/features/personalised-page.feature
- tests/exred/features/top-importers.feature
- tests/exred/pages/article_common.py
- tests/exred/pages/footer.py
- tests/exred/pages/home.py
- tests/exred/pages/triage_summary.py
- tests/exred/steps/given_def.py
- tests/exred/steps/then_def.py
- tests/exred/steps/then_impl.py
- tests/exred/steps/when_impl.py
These tickets:
* [ED-2656](https://uktrade.atlassian.net/browse/ED-2656)
* [ED-2593](https://uktrade.atlassian.net/browse/ED-2593)
* [ED-2591](https://uktrade.atlassian.net/browse/ED-2591)
Scenario:
```gherkin
@ED-2656
@<social-media>
Scenario Outline: Any Exporter should be able to share the Case Study Article via "<social-media>"
Given "Robert" is on the Case Study page accessed via "Home" page
When "Robert" decides to share the article via "<social-media>"
Then "Robert" should be taken to a new tab with the "<social-media>" share page opened
And "Robert" should that "<social-media>" share page has been pre-populated with message and the link to the article
Examples:
| social-media |
| Facebook     |
| Twitter      |
| LinkedIn     |
@ED-2656
@email
Scenario: Any Exporter should be able …
```
> ED-2656, ED-2593, ED-2591 share case study and related scenarios

- tests/exred/environment.py
- tests/exred/features/accessing-services.feature
- tests/exred/pages/header.py
- tests/exred/pages/home.py
- tests/exred/pages/selling_online_overseas.py
- tests/exred/pages/share_on_facebook.py
- tests/exred/pages/share_on_linkedin.py
- tests/exred/pages/share_on_twitter.py
- tests/exred/pages/sso_registration.py
- tests/exred/utils/__init__.py
- tests/functional/features/fab/profile.feature
- tests/functional/steps/fab_when_impl.py
- tests/functional/utils/db_utils.py
This [ticket](https://uktrade.atlassian.net/browse/ED-3112)
- fix db clean-up scripts
- improve ExRed UI test reliability by adding an implicit "wait for visibility" action executed of every attempt of finding a web element
- other minor tweaks
> ED-3112 Improve stability of FAB & ExRed tests & Update scenario tags

- makefile
- tests/exred/features/home-page.feature
- tests/exred/features/international-page.feature
- tests/exred/pages/language_selector.py
- tests/exred/registry/articles.py
- tests/exred/steps/then_def.py
- tests/exred/steps/then_impl.py
- tests/exred/steps/when_def.py
- tests/exred/steps/when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/ED-3149)
Scenarios:
```gherkin
@ED-3149
@language-selector
Scenario Outline: Visitors should be able to view International page in "<preferred_language>"
Given "Robert" visits the "International" page
When "Robert" decides to view the page in "<preferred_language>"
Then "Robert" should be on the "International" page
And "Robert" should see the page in "<preferred_language>"
Examples: available languages
| preferred_language |
| English            |
| 简体中文            |
| Deutsch            |
| 日本語              |
| Español            |
| Português          |
| العربيّة            |
@ED-3149
@language-selector
Scenario: Visitors should be able to "get guidance and services to help them export" (visit ExRed) from International page
Given …
```
> ED-3149 change language on international & domestic page

- tests/exred/features/header-footer.feature
- tests/exred/pages/article_common.py
- tests/exred/pages/article_list.py
- tests/exred/pages/personalised_journey.py
- tests/exred/pages/triage_create_your_export_journey.py
- tests/exred/steps/then_impl.py
- tests/exred/steps/when_def.py
This PR includes 8 scenarios from this [ticket](https://uktrade.atlassian.net/browse/ED-3222)
* [ED-3283](https://uktrade.atlassian.net/browse/ED-3283)
* [ED-3284](https://uktrade.atlassian.net/browse/ED-3284)
* [ED-3285](https://uktrade.atlassian.net/browse/ED-3285)
* [ED-3286](https://uktrade.atlassian.net/browse/ED-3286)
* [ED-3287](https://uktrade.atlassian.net/browse/ED-3287)
* [ED-3288](https://uktrade.atlassian.net/browse/ED-3288)
* [ED-3289](https://uktrade.atlassian.net/browse/ED-3289)
* [ED-3290](https://uktrade.atlassian.net/browse/ED-3290)
Scenarios:
```gherkin
@ED-3283
@your-export-journey-link
@<specific>
Scenario Outline: Any user who has created his/her "Personalised Journey page" should be able to return to it using "Your export journey" link
Given "Robert" answered …
```
> ED-3222 remaining scenarios for your export journey link

- .circleci/config.yml
- tests/__init__.py
- tests/exred/config/browserstack-single.json
- tests/functional/features/fab/multiuser-accounts.feature
- tests/functional/pages/fab_ui_account_add_collaborator.py
- tests/functional/registry/__init__.py
- tests/functional/steps/fab_given_def.py
- tests/functional/steps/fab_given_impl.py
- tests/functional/steps/fab_then_def.py
- tests/functional/steps/fab_then_impl.py
- tests/functional/steps/fab_when_def.py
- tests/functional/steps/fab_when_impl.py
- tests/functional/utils/generic.py
- tests/settings.py
This [ticket](https://uktrade.atlassian.net/browse/ED-3554)
Scenario:
```gherkin
@ED-3554
@multi-user
@add-collaborator
Scenario Outline: Invited collaborator should receive an email with an invitation to collaborate to "<a>" company profile
Given "Peter Alder" has created "<a>" profile for randomly selected company "Y"
And "Annette Geissinger" "<has or does not have>" an SSO/great.gov.uk account
When "Peter Alder" decides to add "Annette Geissinger" as a collaborator
Then "Annette Geissinger" should receive an email with a request for becoming a collaborator to company "Y" profile
Examples:
| a             | has or does not have |
| a verified    | has                  |
| a verified    | does not have        |
| an unverified | has                  |
| an unverified | does not have …
```
> ED-3554 Invited collaborator should receive an email with an invitation to edit the company's profile

- scripts/geckoboard_updater.py
This [ticket](https://uktrade.atlassian.net/browse/ED-3610)
Ignore jobs triggered by geckoboard updater when fetching the list of recent builds.
> ignore jobs run by geckoboard updater workflow

- scripts/geckoboard_updater.py
This [ticket](https://uktrade.atlassian.net/browse/ED-3659)
An example dataset sent to Geckoboard:
```json
[{"closed": 11, "date": "2018-05-15"}]
````
> ED-3659 get number of bugs closed today and push it to geckoboard

- tests/browser/features/invest/industry.feature
- tests/browser/pages/invest_industry.py
- tests/browser/steps/when_def.py
- tests/browser/steps/when_impl.py
Scenario:
```gherkin
@CMS-160
Scenario Outline: Visitors should be able to see the "Invest - <selected> industry" page
Given "Robert" visits the "Invest - <selected> industry" page
When "Robert" unfolds all topic sections on "Invest - <selected> industry" page
Then "Robert" should see expected sections on "Invest - <selected> industry" page
| Sections         |
| Header           |
| Beta bar         |
| Hero             |
| Industry pullout |
| Big number       |
| Topics           |
| Topics contents  |
| Report this page |
| Footer           |
Examples: Industries
| selected                            |
| Advanced manufacturing              |
| Aerospace                           |
| Agri-tech                           |
| Asset …
```
> CMS-160 invest - automate scenarios for indutry pages

- requirements_browser.in
- requirements_browser.txt
- tests/__init__.py
- tests/browser/features/invest/hpo_pdfs.feature
- tests/browser/pages/invest/hpo_contact_us_thank_you.py
- tests/browser/steps/given_def.py
- tests/browser/steps/then_def.py
- tests/browser/steps/then_impl.py
- tests/browser/steps/when_def.py
- tests/browser/steps/when_impl.py
- tests/browser/utils/pdf.py
- tests/smoke/test_api.py
- tests/smoke/test_profile.py
- tests/smoke/test_sso_api.py
Scenario:
```gherkin
@TT-444
Scenario Outline: Check PDFs listed on "Thank you for your enquiry" page
Given "Peter Alder" got in touch with us via "Invest - <selected> - HPO Contact Us" page
And "Peter Alder" is on the "Invest - Thank you for your enquiry - HPO Contact us" page
When "Peter Alder" downloads all visible PDFs
Then "Peter Alder" should see correct details in every downloaded PDF
| telephone number = +44(0) 207 000 9012    |
| email address = enquiries@invest-trade.uk |
And there should not be any dead links in every downloaded PDF
Examples:
| selected                          |
| High productivity food production |
@full
Examples:
| selected                          |
| Lightweight structures            |
| Rail …
```
> TT-444 check pdf links

- .circleci/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- tests/browser/features/exred/accessing-services.feature
- tests/browser/features/exred/advice.feature
- tests/browser/pages/exred/advice_article.py
- tests/browser/pages/exred/article_list.py
- tests/browser/pages/exred/footer.py
- tests/browser/pages/exred/header.py
- tests/browser/pages/exred/home.py
- tests/browser/steps/given_def.py
- tests/browser/steps/then_def.py
- tests/browser/steps/then_impl.py
- tests/browser/steps/when_def.py
- tests/browser/steps/when_impl.py
This [ticket](https://uktrade.atlassian.net/browse/CMS-686)
Scenario:
```gherkin
@CMS-686
Scenario Outline: Any Exporter visiting the home page should be able to see links to all Advice categories in "Export Readiness - <link_location>"
Given "Robert" visits the "Export Readiness - Home" page
Then "Robert" should see links to following "Advice" categories in "Export Readiness - <link_location>"
| categories                                  |
| Create an export plan                       |
| Find an export market                       |
| Define route to market                      |
| Get export finance and funding              |
| Manage payment for export orders            |
| Prepare to do business in a foreign country |
| Manage legal and ethical compliance         |
| Prepare for …
```
> CMS-686 new scenarios and cleanup
